force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Ciudad correspondiente a la ubicación</description>
    <inlineHelpText>Ciudad correspondiente a la ubicación</inlineHelpText>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Código Postal correspondiente a la ubicación</description>
    <inlineHelpText>Código Postal correspondiente a la ubicación</inlineHelpText>
    <label>Postal Code</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Estado correspondiente a la ubicación</description>
    <inlineHelpText>Estado correspondiente a la ubicación</inlineHelpText>
    <label>State</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Calle correspondiente a la ubicación</description>
    <inlineHelpText>Calle correspondiente a la ubicación</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Verified__c.field-meta.xml
<CustomField>
    <fullName>Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Expone si la ubicación esta verificada mediante callouts a la API SmartyStreets</description>
    <inlineHelpText>Indica si la ubicación esta verificada o no.</inlineHelpText>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QueueableVerifyLocation.cls
public with sharing class QueueableVerifyLocation implements Queueable, Database.AllowsCallouts {
    
    public List<Location__c> newLocationsList;
    
    public QueueableVerifyLocation(List<Location__c> triggerList) {
        this.newLocationsList = triggerList;
    }

    public void execute(QueueableContext qc) {

        List<Location__c> locationObjVerified = new List<Location__c>();
        for (Location__c locationObj : newLocationsList) {

            String baseURL = 'https://us-street.api.smartystreets.com/street-address?auth-id=7a5f1152-2dba-ddb7-689b-1f39d3c6db01&auth-token=DRi1fbMg91UQURe8h0uF';
            String endpoint = baseURL + '&street='+EncodingUtil.urlEncode(locationObj.Street__c, 'UTF-8') + '&city='+EncodingUtil.urlEncode(locationObj.City__c, 'UTF-8') + '&state='+EncodingUtil.urlEncode(locationObj.State__c, 'UTF-8') + '&zipcode='+EncodingUtil.urlEncode(locationObj.Postal_Code__c, 'UTF-8') + '&match=enhanced';

            HttpRequest request = new HttpRequest();
            request.setMethod('GET');
            request.setEndpoint(endpoint);
            request.setHeader('Content-Type', 'application/json');
    
            Http http = new Http();
            
            try {
                HttpResponse response = http.send(request);
                if (response.getStatus() == 'OK' && response.getStatusCode() == 200) {
                    String responseBody = response.getBody();
                    Location__c newLocation = locationObj.clone(true, false, false, false);
                    if (!String.isBlank(responseBody) && responseBody.length() > 2) {
                        newLocation.Verified__c = true;
                    } else {
                        newLocation.Verified__c = false;
                    }
                    locationObjVerified.add(newLocation);
                } else {
                    TransactionLogHandler.exceptionHandlerWithError(response.getBody(), 'LocationTriggerHandler');
                }
            } catch (Exception except) {
                TransactionLogHandler.exceptionHandler(except, 'LocationTriggerHandler');
            }
            
        }
        update locationObjVerified;
    }
}