force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransactionLogHandlerTest.cls
@isTest
public with sharing class TransactionLogHandlerTest {

    @isTest
    static void exceptionHandlerTest() {
        try {
            Integer i = 10/0;
        } catch (Exception except) {
            Test.startTest();
            TransactionLogHandler.exceptionHandler(except, 'ProcessPrueba');
            Test.stopTest(); 
        }

        List<Error_Log__c> errorLogs = [SELECT Id, Process_Name__c FROM Error_Log__c WHERE Process_Name__c = 'ProcessPrueba'];
        System.assertEquals(1, errorLogs.size(), 'Objeto creado correctamente.');
    }

    @isTest
    static void exceptionHandlerWithErrorTest() {
        Test.startTest();
        TransactionLogHandler.exceptionHandlerWithError('ErrorPrueba', 'ProcessWithErrorPrueba');
        Test.stopTest(); 

        List<Error_Log__c> errorLogs = [SELECT Id, Process_Name__c FROM Error_Log__c WHERE Process_Name__c = 'ProcessWithErrorPrueba'];
        System.assertEquals(1, errorLogs.size(), 'Objeto creado correctamente.');
    }
}