force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <description>Store the Date &amp; Time details when the Error Occurred</description>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Ciudad correspondiente a la ubicación</description>
    <inlineHelpText>Ciudad correspondiente a la ubicación</inlineHelpText>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>País correspondiente a la ubicación</description>
    <inlineHelpText>País correspondiente a la ubicación</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Código Postal correspondiente a la ubicación</description>
    <inlineHelpText>Código Postal correspondiente a la ubicación</inlineHelpText>
    <label>Postal Code</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Estado correspondiente a la ubicación</description>
    <inlineHelpText>Estado correspondiente a la ubicación</inlineHelpText>
    <label>State</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Calle correspondiente a la ubicación</description>
    <inlineHelpText>Calle correspondiente a la ubicación</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Verified__c.field-meta.xml
<CustomField>
    <fullName>Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Expone si la ubicación esta verificada mediante callouts a la API SmartyStreets</description>
    <inlineHelpText>Indica si la ubicación esta verificada o no.</inlineHelpText>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QueueableVerifyLocationTest.cls
@isTest
public class QueueableVerifyLocationTest{

    @isTest
    static void verifyLocationTest(){
        Test.setMock(HttpCalloutMock.class, new LocationHttpCalloutMock('OK'));

        List<Location__c> locationList = new List<Location__c>();
        Location__c locationObj = new Location__c(
            Name = 'Location Test',
            Street__c = 'Uruguay',
            State__c = 'Buenos Aires',
            City__c = 'Bahia Blanca',
            Postal_Code__c = '8000',
            Country__c = 'Argentina'
        );
        insert locationObj;
        locationList.add(locationObj);

        Test.startTest();
        Id jobID = System.enqueueJob(new QueueableVerifyLocation(locationList));
        Test.stopTest();
        
        AsyncApexJob jobInfo = [SELECT Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobID];
        System.assertEquals('Completed', jobInfo.Status, 'Queueable Job creado');
        Location__c location = [SELECT Id, Verified__c FROM Location__c WHERE Id = :locationObj.Id];
        System.assertEquals(true, location.Verified__c, 'La ubicacion esta verificada');
    }

    @isTest
    static void verifyLocationFalseTest(){
        Test.setMock(HttpCalloutMock.class, new LocationHttpCalloutMock('Empty Body'));

        List<Location__c> locationList = new List<Location__c>();
        Location__c locationObj = new Location__c(
            Name = 'Location Test',
            Street__c = 'Uruguay',
            State__c = 'Buenos Aires',
            City__c = 'Bahia Blanca',
            Postal_Code__c = '8000',
            Country__c = 'Argentina'
        );
        insert locationObj;
        locationList.add(locationObj);

        Test.startTest();
        Id jobID = System.enqueueJob(new QueueableVerifyLocation(locationList));
        Test.stopTest();
        
        AsyncApexJob jobInfo = [SELECT Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobID];
        System.assertEquals('Completed', jobInfo.Status, 'Queueable Job creado');
        Location__c location = [SELECT Id, Verified__c FROM Location__c WHERE Id = :locationObj.Id];
        System.assertEquals(false, location.Verified__c, 'La ubicacion no esta verificada');
        List<Error_Log__c> errorLogs = [SELECT Id, Process_Name__c, Log_Date_Time__c FROM Error_Log__c WHERE Process_Name__c = 'LocationTriggerHandler' AND Log_Date_Time__c = TODAY];
        System.assertEquals(0, errorLogs.size(), 'No se crearon Error Log');
    }

    @isTest
    static void verifyLocationExceptionWithErrorTest(){
        Test.setMock(HttpCalloutMock.class, new LocationHttpCalloutMock('Bad Request'));

        List<Location__c> locationList = new List<Location__c>();
        Location__c locationObj = new Location__c(
            Name = 'False',
            Street__c = 'False',
            State__c = 'False',
            City__c = 'False',
            Postal_Code__c = 'False',
            Country__c = 'Argentina'
        );
        locationList.add(locationObj);

        Test.startTest();
        Id jobID = System.enqueueJob(new QueueableVerifyLocation(locationList));
        Test.stopTest();
        
        AsyncApexJob jobInfo = [SELECT Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobID];
        System.assertEquals('Completed', jobInfo.Status, 'Queueable Job creado');
        List<Error_Log__c> errorLogs = [SELECT Id, Process_Name__c, Log_Date_Time__c FROM Error_Log__c WHERE Process_Name__c = 'LocationTriggerHandler' AND Log_Date_Time__c = TODAY];
        System.assertEquals(1, errorLogs.size(), 'Se creo correctamente el Error Log');
    }
    
    @isTest
    static void verifyLocationExceptionTest(){
        List<Location__c> locationList = new List<Location__c>();
        for(Integer i=0; i < 10; i++) {
            locationList.add(new Location__c(
                Name = 'Location Test' + i,
                Street__c = 'Street' + i,
                City__c = 'Bahia Blanca',
                State__c = 'Buenos Aires',
                Postal_Code__c = '800' + i,
                Country__c = 'Argentina'
            ));
        }

        Test.startTest();
        Id jobID = System.enqueueJob(new QueueableVerifyLocation(locationList));
        Test.stopTest();
        
        AsyncApexJob jobInfo = [SELECT Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobID];
        System.assertEquals('Completed', jobInfo.Status, 'Queueable Job creado');
        List<Error_Log__c> errorLogs = [SELECT Id, Process_Name__c, Log_Date_Time__c FROM Error_Log__c WHERE Process_Name__c = 'LocationTriggerHandler' AND Log_Date_Time__c = TODAY];
        System.System.debug(errorLogs);
        System.assertEquals(10, errorLogs.size(), 'Error Logs creados');
    }

}