force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <description>Store the Date &amp; Time details when the Error Occurred</description>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Stores the Complete Stack Track about the Problem</description>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransactionLogHandler.cls
public with sharing class TransactionLogHandler {
    public static void exceptionHandler(System.Exception except, String processName) {
        Error_Log__c transactionLog = new Error_Log__c(
            Log_Details__c = except.getCause() + '<br>' + except.getLineNumber() + '<br>' + except.getMessage() + '<br>' + except.getStackTraceString() + '<br>' + except.getTypeName(),
            Log_Date_Time__c = System.now(),
            Process_Name__c = processName
        );

        if (Error_Log__c.SObjectType.getDescribe().isCreateable()) {
            insert transactionLog;
        }
    }

    public static void exceptionHandlerWithError(String error, String processName) {
        Error_Log__c transactionLog = new Error_Log__c(
            Log_Details__c = error,
            Log_Date_Time__c = System.now(),
            Process_Name__c = processName
        );

        if (Error_Log__c.SObjectType.getDescribe().isCreateable()) {
            insert transactionLog;
        }
    }
}