force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <description>Posible asistente a eventos</description>
    <label>Attendees</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Mail del asistente</description>
    <inlineHelpText>Mail del asistente</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Attendees__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Telefono del asistente</description>
    <inlineHelpText>Telefono del asistente</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Representa un evento planificado en un lugar especifico, con asistentes, un organizador y presentadores</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>Fecha en que finaliza el periodo de confirmación de asistencia</description>
    <inlineHelpText>Fecha en que finaliza el periodo de confirmación de asistencia</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo completado mediante una relación Master-Detail con el objeto Event Organizer</description>
    <inlineHelpText>Organizador del evento</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Capacidad máxima de asistentes</description>
    <inlineHelpText>Capacidad máxima de asistentes</inlineHelpText>
    <label>Max Seats</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Fecha en que comienza el periodo de confirmación de asistencia</description>
    <inlineHelpText>Fecha en que comienza el periodo de confirmación de asistencia</inlineHelpText>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>Representa un asistente al evento organizado</description>
    <label>Event Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <description>Campo completado con una relación Master-Detail con el objeto Attendee</description>
    <inlineHelpText>Asistente al evento</inlineHelpText>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Campo completado mediante una relación Master-Detail con el objeto Event</description>
    <inlineHelpText>Evento organizado</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Representa un organizador de eventos</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Mail principal</description>
    <inlineHelpText>Mail principal</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Telefono principal</description>
    <inlineHelpText>Telefono principal</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/EventAttendeeTriggerTest.cls
@isTest
public with sharing class EventAttendeeTriggerTest {

    @TestSetup
    static void setupData(){
        Event_Organizer__c eventOrganizer = new Event_Organizer__c(
            Name = 'EventOrganizer Prueba',
            Email__c = 'eventorgmail@salesforce.com',
            Phone__c = '221454545'
        );
        insert eventOrganizer;

        Event__c event = new Event__c(
            Name = 'Evento Prueba',
            Event_Organizer__c = eventOrganizer.Id,
            Start_Date_Time__c = System.now(),
            End_Date_Time__c = System.now().addDays(5),
            Max_Seats__c = 20000,
            Live__c = true
        );
        insert event;

        Attendees__c attendee = new Attendees__c(
            Name = 'Attendee Prueba',
            Email__c = 'attendeemail@salesforce.com',
            Phone__c = '221656565'
        );        
        insert attendee;

    }

    @isTest
    static void sendEmailConfirmaitionTest() {
        Event__c event = [SELECT Id, Name FROM Event__c WHERE Name = 'Evento Prueba' LIMIT 1]; 
        Attendees__c attendee = [SELECT Id, Name FROM Attendees__c WHERE Name = 'Attendee Prueba' LIMIT 1];
        Event_Attendee__c eventAttendee = new Event_Attendee__c(
            Name = 'Event Attendee Prueba',
            Event__c = event.Id,
            Attendees__c = attendee.Id
        );

        Test.startTest();
        insert eventAttendee;
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();

        List<Error_Log__c> transactionLogs = [SELECT Id, Process_Name__c FROM Process_Name__c WHERE Process_Name__c = 'EventAttendeeTriggerHandler'];
        System.assertEquals(1, emailInvocations, 'Mail enviado correctamente.');
    
    }
}