force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <description>Posible asistente a eventos</description>
    <label>Attendees</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dirección vivienda del asistente</description>
    <inlineHelpText>Dirección vivienda del asistente</inlineHelpText>
    <label>Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendees__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Mail del asistente</description>
    <inlineHelpText>Mail del asistente</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Attendees__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Telefono del asistente</description>
    <inlineHelpText>Telefono del asistente</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Representa un evento planificado en un lugar especifico, con asistentes, un organizador y presentadores</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo completado mediante una relación Master-Detail con el objeto Event Organizer</description>
    <inlineHelpText>Organizador del evento</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo completado mediante una relación Lookup con el objecto Location</description>
    <inlineHelpText>Ubicación en que se llevara a cabo el evento</inlineHelpText>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Fecha en que comienza el periodo de confirmación de asistencia</description>
    <inlineHelpText>Fecha en que comienza el periodo de confirmación de asistencia</inlineHelpText>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>Representa un asistente al evento organizado</description>
    <label>Event Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <description>Campo completado con una relación Master-Detail con el objeto Attendee</description>
    <inlineHelpText>Asistente al evento</inlineHelpText>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Campo completado mediante una relación Master-Detail con el objeto Event</description>
    <inlineHelpText>Evento organizado</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Representa un organizador de eventos</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeTriggerHandler.cls
public without sharing class EventAttendeeTriggerHandler {

    public static void sendConfirmationEmail(List<Event_Attendee__c> eventAttendeesList) {

        List<Id> eventAttendeesID = new List<Id>();
        for (Event_Attendee__c eventAttendee : eventAttendeesList) {
            eventAttendeesID.add(eventAttendee.Id);
        }

        List<Event_Attendee__c> eventAttendeesQuery = [SELECT Id, Attendees__r.Name, Attendees__r.Email__c, Attendees__r.Phone__c, Event__r.Name, Event__r.Start_Date_Time__c, Event__r.Location__r.Name, Event__r.Location__r.Street__c, Event__r.Location__r.City__c, Event__r.Location__r.State__c, Event__r.Location__r.Postal_Code__c, Event__r.Location__r.Country__c, Event__r.Event_Organizer__r.Name FROM Event_Attendee__c WHERE Id IN :eventAttendeesID WITH SECURITY_ENFORCED];

        // Se crea una lista de mails a enviar
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();

        for (Event_Attendee__c eventAttendee : eventAttendeesQuery) {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

            email.setToAddresses(new List<String>{ eventAttendee.Attendees__r.Email__c });
            email.setSubject('Pass for the ' + eventAttendee.Event__r.Name);
            email.setSenderDisplayName(eventAttendee.Event__r.Event_Organizer__r.Name);

            String location = 'https://www.google.com/maps/place/'+eventAttendee.Event__r.Location__r.Street__c+' '+eventAttendee.Event__r.Location__r.City__c+' '+eventAttendee.Event__r.Location__r.State__c+' '+eventAttendee.Event__r.Location__r.Country__c+' '+eventAttendee.Event__r.Location__r.Postal_Code__c;
            String hrefForLocation = '<a href="'+location+'"'+'target="_blank">aca</a>';
            String emailBody = 'Hola ' + eventAttendee.Attendees__r.Name + ', <br/>' +
            'Gracias por inscribirte para el evento ' + eventAttendee.Event__r.Name + ' el dia ' + eventAttendee.Event__r.Start_Date_Time__c + ' que tendra lugar en ' + eventAttendee.Event__r.Location__r.Name + '. Estamos emocionados de contar con tu participacion!. <br/>' +
            'Puedes encontrar la ubicacion del evento en Google Maps ' + hrefForLocation + '.<br/><br/><br/>' + 'Saludos, <br/>' +eventAttendee.Event__r.Event_Organizer__r.Name;

            email.setHtmlBody(emailBody);
            // Se agrega el mail creado a la lista
            emailList.add(email);
        }

        try {
            List<Messaging.SendEmailResult> results =  Messaging.sendEmail(emailList, false); 
            for(Messaging.SendEmailResult email : results){
                if(!email.isSuccess()){
                    List<Messaging.SendEmailError> errors = email.getErrors();
                    TransactionLogHandler.exceptionHandlerWithError(JSON.serialize(errors), 'EventAttendeeTriggerHandler');
                }
            }  
        } catch (System.Exception except) {
            TransactionLogHandler.exceptionHandler(except, 'EventAttendeeTriggerHandler');
        } 

    }

}