force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Representa un evento planificado en un lugar especifico, con asistentes, un organizador y presentadores</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>Fecha en que finaliza el periodo de confirmación de asistencia</description>
    <inlineHelpText>Fecha en que finaliza el periodo de confirmación de asistencia</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo completado mediante una relación Master-Detail con el objeto Event Organizer</description>
    <inlineHelpText>Organizador del evento</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Capacidad máxima de asistentes</description>
    <inlineHelpText>Capacidad máxima de asistentes</inlineHelpText>
    <label>Max Seats</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Fecha en que comienza el periodo de confirmación de asistencia</description>
    <inlineHelpText>Fecha en que comienza el periodo de confirmación de asistencia</inlineHelpText>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Representa un organizador de eventos</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Mail principal</description>
    <inlineHelpText>Mail principal</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Telefono principal</description>
    <inlineHelpText>Telefono principal</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/DeleteEventBatchTest.cls
@isTest
public class DeleteEventBatchTest {

    @TestSetup
    static void setupData(){
        Event_Organizer__c organizer = new Event_Organizer__c(
            Name = 'Organizer',
            Email__c = 'organizer@prueba.com',
            Phone__c = '221454454'
        );
        insert organizer;

        List<Event__c> eventList = new List<Event__c>();
        for (Integer i = 0; i<200; i++) {
            eventList.add(new Event__c(
                Name = 'Event Prueba' + i,
                Event_Organizer__c = organizer.Id,
                Start_Date_Time__c = System.now().addMonths(-4),
                End_Date_Time__c = System.now().addDays(15).addMonths(-4),
                Max_Seats__c = 20000
            ));
        }
        insert eventList; 
    }

    @isTest
    static void deleteEventTest() {
        Test.startTest();
        String nameString = 'Event Prueba%';
        System.assertEquals(200, Database.query('SELECT Id, Name, End_Date_Time__c FROM Event__c WHERE Name LIKE :nameString').size(), 'Para comprobar si efectivamente se crearon los objetos desde setupData');

        Id batchId = Database.executeBatch(new DeleteEventBatch(), 250);
        Test.stopTest();

        Datetime checkDate = System.now().addMonths(-2);
        List<Event__c> events = [SELECT Id, End_Date_Time__c FROM Event__c WHERE End_Date_Time__c < :checkDate];
        System.assertEquals(0, events.size(), 'Todos los eventos eliminados');
    }
}