force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Representa un evento planificado en un lugar especifico, con asistentes, un organizador y presentadores</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <description>Presentador del evento organizado</description>
    <label>Event Speaker</label>
    <nameField>
        <label>Event Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Campo completado mediante una relación Master-Detail con el objeto Event</description>
    <inlineHelpText>Evento organizado</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Campo completado mediante una relacion Master-Detail con el objeto Speaker</description>
    <inlineHelpText>Presentador del evento</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>Posibles presentadores de eventos</description>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Compañía a la que pertenece</description>
    <inlineHelpText>Compañía a la que pertenece</inlineHelpText>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Mail de contacto del presentador</description>
    <inlineHelpText>Mail de contacto</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Telefono de contacto del presentador</description>
    <inlineHelpText>Telefono de contacto</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/EventDetailController.cls
public with sharing class EventDetailController {

    @AuraEnabled(cacheable=true)
    public static List<Event_Speaker__c> getSpeakers(String eventID) {
        List<Event_Speaker__c> eventSpeakerList = [SELECT Id, Name, Event__c, Speaker__r.Email__c, Speaker__r.Phone__c, Speaker__r.Company__c FROM Event_Speaker__c WHERE Event__c = :eventID WITH SECURITY_ENFORCED];
        return eventSpeakerList;
    }
}